config/routes.rb
Helpdesk::Application.routes.draw do
  resources :tickets do
    resources :replies
  end

  resources :users
  resources :replies, only: :create

  root :to => "tickets#index"

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :reply, :ticket_id
  belongs_to :ticket

  # def self.create_from_inbound_hook(message)
  #   self.create(:ticket_id => message["Subject"].gsub("Re: Help desk ticket has been created, ID ", "").to_i, :reply => message["TextBody"])
  # end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :problem, :title, :name, :email, :reply
  validates_format_of :email, :with => /@/
  has_many :replies

#   def self.update_from_inbound_hook(message)
#     self.update(message["Subject"].gsub("Re: Help desk ticket has been created, ID ", ""), :reply => message["TextBody"])
#   end
end

# Try creating a new model and db for replies and then attr access in the controller (model?) and list in view

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def index
    @replies = Reply.all
  end

  def new
    @reply = Reply.new
  end

  def create
    # @reply_params = JSON.parse(params[:ticket_id => "Subject".gsub("Re: Help desk ticket has been created, ID ", "").to_i, :reply => "TextBody"])
    # @reply = Reply.new.create_from_inbound_hook(Postmark::Json.decode(request.body.read))
    @subject = params["Subject"].gsub("Re: Help desk ticket has been created, ID ", "").to_i
    @body = params["TextBody"]
    @reply = Reply.new(:ticket_id => @subject, :reply => @body)

    @reply.save
    render nothing: true
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, only: :inbound_ticket_reply
  # before_filter :authenticate_postmark, only: [:create]

  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @replies = Reply.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        TicketMailer.help_request(@ticket).deliver
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # def inbound_ticket_reply
  #   @ticket = Ticket.update_from_inbound_hook(Postmark::Json.decode(request.body.read))

  #   respond_to do |format|
  #     if @ticket.save
  #       format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
  #       format.json { render json: @ticket, status: :created, location: @ticket }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @ticket.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket_id = Ticket.find(params[:id])
    # @ticket = Ticket.update_from_inbound_hook(Postmark::Json.decode(request.body.read))

    respond_to do |format|
      if @ticket_id.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label "Type of problem" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :problem %><br />
    <%= f.text_area :problem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Problem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= ticket.title %></td>
    <td><%= ticket.problem %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @ticket.title %>
</p>

<p>
  <b>Problem:</b>
  <%= @ticket.problem %>
</p>

<p>
  <b>Answer to Problem:</b>
  <% @ticket.replies.each do |answer| %>
  <%= answer.reply %>
  <% end %>

</p>

<%= link_to 'Back', tickets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>